// svelte-todo-app/src/lib/Todo.svelte
<script>
    let tasks = [
        { label: "Learn Svelte", id: "1" },
        { label: "Build an app", id: "2" },
        { label: "Deploy to production", id: "3" },
    ];
    let newTask = { label: "", id: "" };

    function addTask() {
        if (newTask.label !== "") {
            tasks = [...tasks, newTask];
            newTask = { label: "", id: String(Math.random() * 1000) };
        }
    }

    function deleteTask(id) {
        tasks = tasks.filter((task) => task.id !== id);
    }
</script>

<h1>Todo List</h1>
<ul>
    {#each tasks as task}
        <li>
            {task.label}
            <button on:click={() => deleteTask(task.id)}>Delete Task</button>
        </li>
    {/each}
</ul>
<input type="text" bind:value={newTask.label} />
<button on:click={addTask}>Add Task</button>

// vue-todo-app/src/components/Todo.vue
<template>
    <div>
        <h1>Todo List</h1>
        <ul>
            <li v-for="(task, index) in tasks" :key="index">{{ task.label }}
                <button @click="deleteTask(task.id)">Delete Task</button>

            </li>
        </ul>
        <input type="text" v-model="newTask.label">
        <button @click="addTask()">Add Task</button>
    </div>
</template>
<script lang="ts">
export default {
    data() {
        return {
            tasks: [{ label: 'Learn Vue.js', id: '1' }, { label: 'Build an app', id: '2' }, { label: 'Deploy to production', id: '3' }],
            newTask: { id: String(Math.random() * 1000), label: "" }
        }
    },
    methods: {
        addTask() {
            if (this.newTask.label !== '') {
                this.tasks.push(this.newTask)
                this.newTask = { id: String(Math.random() * 1000), label: "" }
            }
        },
        deleteTask(id: string) {
            this.tasks = this.tasks.filter(t => t.id !== id)
        }
    }
}
</script>
